Dashboard view with styling
bcgov/nr-spar-webapp pull request #11
Opened 2022-12-06 19:04 UTC by NickSaglioni

# Description

Adding the dashboard page with all required components.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit testing

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2022-12-07 19:03 UTC, RMCampos requested changes

2022-12-07 19:03 UTC, RMCampos commented on src/components/LeftPanel/index.tsx
> +      {listItems.map((item: any) => (
I think we can define an Interface here.

2022-12-07 19:03 UTC, RMCampos commented on src/components/LeftPanel/index.tsx
> +          {item.items.map((subItem: any) => {
I think we can define an Interface here.

2022-12-07 19:03 UTC, RMCampos commented on src/components/LeftPanel/index.tsx
> +import * as Icons from '@carbon/icons-react';
I'm not sure if this is a good idea. I would say that is clearer if we import only the icons that we're going to use.

2022-12-07 19:03 UTC, RMCampos commented on src/types/Activity.ts
> +    last_viewed: string;
I think here there are 4 spaces instead of 2. Take a look on the lint rules.

2022-12-13 15:32 UTC, mgaseta commented on src/components/BCHeader/index.tsx
> +          SPAR Seed Planning and Registry System
Fixed! Thanks for spotting that!

2022-12-14 14:27 UTC, RMCampos approved these changes
Great Job Matheus! 🥳

2022-12-14 17:25 UTC, merged