Feat/highlight
bcgov/nr-spar-webapp pull request #21
Opened 2022-12-26 18:04 UTC by ArthurEncr

# Description

- Style for highlighted favorite card
- Logic to highlight and dehighlight a favorite card
- Global changes to overflow menu
- Changes in the favorites cards mock and card type 
JIRA ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-323

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2022-12-26 20:05 UTC, mgaseta requested changes
Great job 🎉! Add a fez markups mainly related to code style and organization.

2022-12-26 20:05 UTC, mgaseta commented on src/components/FavoriteActivities/styles.css
> +}
I think this has been a conflict resolution after this branch was updated, please revert it back.

2022-12-26 20:05 UTC, mgaseta commented on src/components/RecentActivities/styles.css
> +}
I think this has been a conflict resolution after this branch was updated, please revert it back.

2022-12-26 20:05 UTC, mgaseta commented on src/layout/PublicLayout/styles.css
> +}
I think this has been a conflict resolution after this branch was updated, please revert it back.

2022-12-26 20:05 UTC, mgaseta commented on src/theme/components-overrides.scss
> +}
If this rule is specific only to the card component, it should be moved to the component style file.

2022-12-26 20:05 UTC, mgaseta commented on src/types/Card.ts
> +    highlighted?: boolean;
Adjust tabs here.

2022-12-27 14:52 UTC, RMCampos approved these changes
Great job!! Very good 🥳

2022-12-27 15:08 UTC, mgaseta requested changes

2022-12-27 15:08 UTC, mgaseta commented on src/App.tsx
> +              <ProtectedRoute signed>
Revert this change.

2022-12-27 19:33 UTC, mgaseta approved these changes

2022-12-27 19:58 UTC, merged