Feat/empty sections
bcgov/nr-spar-webapp pull request #27
Opened 2023-01-03 14:30 UTC by ArthurEncr

# Description

Created empty sections component and implemented in recent activities and favorite activities sections

[Jira ticket
](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-347?)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually tested. For recent activities to empty the items and view the change you have to change the "list item" to be an empty array. In favorite activities, just delete all shortcuts.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

An observation is that in the implementation in the sections I used a generic icon for both, but it is not the same as in the mockup. We will have to change in the future.

2023-01-04 14:12 UTC, mgaseta requested changes
Just one change necessary, besides that, great job!

2023-01-04 14:12 UTC, mgaseta commented on src/components/EmptySection/index.tsx
> +    <div className="empty-section-container" style={padding ? { padding: `${padding}px 1rem` } : { padding: '2.375rem 1rem' }}>
I understand the needs of the padding, but using it directly on the style attribute is not a good practice, is there another way to implement this?

2023-01-06 12:22 UTC, RMCampos approved these changes
Good job! LGTM

2023-01-06 17:58 UTC, mgaseta approved these changes
LGTM! 💯 🥇

2023-01-06 18:19 UTC, merged