Feat/theme change
bcgov/nr-spar-webapp pull request #36
Opened 2023-01-30 20:37 UTC by ArthurEncr

# Description
Implemented changing themes, between light mode and dark mode. I had to change several project files to use token variables. Theme switch button has been added to the "my profile" menu temporarily.

- Theme changing logic created 
- Button to change theme at my profile menu
- I changed some lines that used colors without being project variables
- New token created (background-left-panel)
- New variable stored in local storage. (mode)
- New prop added to Panel Section name.

[
Jira Ticket
](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-411?)
## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually tested and unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

I added the change theme button in the "my profile" menu, but when this is developed in the mockup we will change places. I had to create the new token for the left panel after discussions with the UX team. Another task needs to be created to apply the dark theme to notification components, tags and buttons.

2023-01-31 18:01 UTC, RMCampos requested changes
Good job! It looks amazing. However when logging out with dark theme activated the landing page also goes dark. It should keep white.

2023-02-01 11:42 UTC, lucasbuenoencora reviewed
Great Job! Just check the unit tests of BCHeader and App that are failing in the unit tests check.

2023-02-02 13:48 UTC, mgaseta requested changes
Good job! Just 2 small markups (Besides Lucas' notes). 🚀

2023-02-02 13:48 UTC, mgaseta commented on src/views/Dashboard/dashboard.tsx
> +
Remove empty line.

2023-02-02 13:48 UTC, mgaseta commented on src/views/Dashboard/dashboard.tsx
> +
Remove empty line.

2023-02-06 17:11 UTC, mgaseta requested changes
Good job! Just some small changes regarding code documentation. Also, take a look at the conflicts.

2023-02-06 17:11 UTC, mgaseta commented on src/utils/ThemePreference.tsx
> +/** */
Fix documentation here.

2023-02-06 17:11 UTC, mgaseta commented on src/utils/ThemePreference.tsx
> + */
Fix documentation here.

2023-02-06 17:20 UTC, RMCampos requested changes

2023-02-06 17:20 UTC, RMCampos commented on src/utils/ThemePreference.tsx
> +/** */
I think you forgot to add the function description here.

2023-02-06 17:20 UTC, RMCampos commented on src/utils/ThemePreference.tsx
> + * @param root0.children
You could use references to the parameters, using a notation like `children {ReactNode} nodes to be rendered.` Also don't forget to include a description to the function.

2023-02-06 17:22 UTC, RMCampos commented
Good job! 🥳 Only few things related to JSDoc.

2023-02-08 13:46 UTC, mgaseta approved these changes
LGTM!

2023-02-08 13:57 UTC, lucasbuenoencora approved these changes
Great Job!

2023-02-08 13:59 UTC, RMCampos approved these changes
Looks perfect! 🥇

2023-02-08 14:01 UTC, merged