Feat/seedlot feedback page
bcgov/nr-spar-webapp pull request #46
Opened 2023-02-16 13:59 UTC by ArthurEncr

# Description

Seedlot created feedback page created.

[Jira ticket 
](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-477)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-02-17 18:39 UTC, RMCampos approved these changes
LGTM

2023-02-17 19:32 UTC, mgaseta requested changes
Good job 🚀✔! Just added a few markups, mostly related to code patterns, so no worries.

2023-02-17 19:32 UTC, mgaseta commented on src/views/SeedlotCreatedFeedback/index.tsx
> +
Remove empty line.

2023-02-17 19:32 UTC, mgaseta commented on src/views/SeedlotCreatedFeedback/styles.scss
> +@use '../../theme/variables.scss' as vars;
For the whole page, add an space before the opening bracket on the selectors.

2023-02-17 19:32 UTC, mgaseta commented on src/views/SeedlotCreatedFeedback/styles.scss
> +  color: var(--#{vars.$bcgov-prefix}-focus);
The color defined on the figma file is the primary button color (Light Theme/Button/$button-primary), adjust it here to reflect correctly the design.

2023-02-17 19:32 UTC, mgaseta commented on src/views/SeedlotCreatedFeedback/styles.scss
> +}
Put an empty line in between rules.

2023-02-17 19:32 UTC, mgaseta commented on src/views/SeedlotCreatedFeedback/styles.scss
> +}
Adjust tabs here.

2023-02-17 19:32 UTC, mgaseta commented on src/views/SeedlotCreatedFeedback/styles.scss
> +}
Adjust tabs here.

2023-02-17 19:32 UTC, mgaseta commented on src/views/SeedlotDashboard/styles.css
> +  color: var(--bcgov-focus);
Why change the color here?

2023-02-17 20:32 UTC, RMCampos commented on src/App.tsx
> +            path="/seedlot-feedback"
Great point! I would suggest `/seedlot/successfully-created`.

2023-02-23 19:54 UTC, lucasbuenoencora requested changes
LGTM! I guess that after the merge the new component is on the wrong directory, just need to put it inside the frontend folder.

2023-02-24 14:00 UTC, lucasbuenoencora approved these changes
Great Job :rocket: :heavy_check_mark:

2023-02-24 14:01 UTC, merged