feat: extraction and storage page
bcgov/nr-spar-webapp pull request #81
Opened 2023-03-31 20:27 UTC by Wennio-Oliveira

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-04-17 17:17 UTC, RMCampos approved these changes
LGTM

2023-04-18 13:10 UTC, mgaseta requested changes
Great job 🚀🎉! Added some simple markups only.

2023-04-18 13:10 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/index.tsx
> +} from './definitions';
Adjust imports order, these should be before the styles import.

2023-04-18 13:10 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/styles.scss
> +.seedlot-registration-forms.bcgov--row {
Use `#{vars.$bcgov-prefix}` instead of `bcgov` directly, please fix on other places in this file.

2023-04-18 13:10 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/styles.scss
> +  .bcgov--modal-content {
Use `#{vars.$bcgov-prefix}` instead of `bcgov` directly, please fix on other places in this file.

2023-04-18 19:26 UTC, mgaseta approved these changes
Nice job! 🎉👏

2023-04-18 20:02 UTC, merged