Read only form review
bcgov/nr-spar-webapp pull request #83
Opened 2023-04-13 17:08 UTC by ArthurEncr

At the seedlot details page, users'll be able to review the registration form in a read-only format. 
- Form review items filled with components (at seedlot details page)
- Read only logic added to the register step components
- Mocked data

[Jira ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-614?)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-04-14 15:37 UTC, mgaseta requested changes
Nice job 😎! Added a few markups and doubts, we can arrange a call to go through them, if necessary. Also, there are a few sizing bugs with the forms inside a minor space, like this: 
![image](https://user-images.githubusercontent.com/105936322/232089630-9b40b457-55dc-410b-a780-68a9e5f816cb.png)
And the read-only steps should only appear after the user finishes the said step in the registration flux.

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/FormReview/index.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Remove this line and fix the unused vars (if any).

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/FormReview/index.tsx
> +import OwnershipStep from '../SeedlotRegistrationSteps/OwnershipStep';
Adjust importing order, components imports should be before the style import.

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/FormReview/index.tsx
> +                key={0}
If we are not using the map anymore, the key prop is not necessary.

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/FormReview/index.tsx
> +          Form review
I think these string values can already be passed to a `constants.ts` file, look at the Ownership Step for reference. This applies to the string values on the accordions also.

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/FormReview/index.tsx
> +    orchardStep: initOrchardState()
You can use the mock variables you created here, instead of setting it with the initial clean values.

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/FormReview/index.tsx
> +                    ownershipData={ownershipMock}
Is this prop really necessary? Shouldn't the state prop (initialized with mock values) be enough? This applies to all form steps components.

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/FormReview/styles.scss
> +  height: 2.5rem;
Is this really necessary? Setting the size prop on the component is not enough?

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +}
Can't the InterimForm type be used here? Instead of creating a new type.

2023-04-14 15:37 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +                : state.agencyName}
This won't be necessary if we use the state directly ;)

2023-04-18 19:00 UTC, RMCampos approved these changes
LGTM

2023-04-18 20:13 UTC, mgaseta requested changes
Nice job 🚀😎! Just 2 small markups :)

2023-04-18 20:13 UTC, mgaseta commented on frontend/src/components/FormReview/constants.ts
> +const inputText = {
I think the variable can be renamed, `inputText` doesn't seems right for the purpose of it.

2023-04-18 20:13 UTC, mgaseta commented on frontend/src/components/FormReview/index.tsx
>                      description="Review collection information"
These parameters can be added to the constant.ts file ;)

2023-04-18 20:16 UTC, lucasbuenoencora requested changes
LGTM ! :rocket: Just take a look at the console while on the Form Review Page, it is giving me a warning:
![image](https://user-images.githubusercontent.com/118561969/232894895-6673de8a-fb39-4c71-9b64-cd4cacd64069.png)

2023-04-19 16:59 UTC, lucasbuenoencora approved these changes
Great Job! :rocket: :medal_sports:

2023-04-19 18:44 UTC, mgaseta approved these changes
Great job! 🎉🐱‍🏍🚀

2023-04-19 23:04 UTC, craigyu commented
@RMCampos extraction step has been merged to main, we should probably create another task on Jira to implement that step to this read only form.

2023-04-20 16:55 UTC, RMCampos commented
> 

@craigyu [Created.](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-642)

2023-04-20 18:34 UTC, mgaseta approved these changes
Great job! 🥇🐱‍🏍🎉

2023-04-20 19:31 UTC, merged