test: create seedlot registration test and minor fixes
bcgov/nr-spar-webapp pull request #84
Opened 2023-04-14 17:20 UTC by Wennio-Oliveira

# Description

It was created a flow to cover some scenarios during the Seedlot registration process and did some minor fixes requested by lint

# How Has This Been Tested?

It was tested locally using SparWebApp on test environment

![seedlotRegistration03](https://user-images.githubusercontent.com/118473401/232113629-be7ca776-63b0-4e85-b54b-773c4ae45045.gif)

## Checklist

- [ x ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-04-17 16:46 UTC, iatdaitan approved these changes

2023-04-17 17:32 UTC, RMCampos reviewed
This new test case is failing for me.

2023-04-17 17:45 UTC, RMCampos requested changes

2023-04-17 17:45 UTC, RMCampos commented on frontend/cypress/support/commands.ts
> +    .type(USERNAME, { delay: 50 });
Can you please update the `README.md` file with the correct name of the cypress environment variables?

2023-04-18 13:00 UTC, mgaseta approved these changes
Besides, Ricardo's markups, LGTM!

2023-04-19 13:42 UTC, RMCampos approved these changes
LGTM! Good job 😎

2023-04-19 13:57 UTC, merged